print("Student info")
Name = input("What is your name ? -> ")
Age = int(input("What is your age ? -> "))
College = input("What is your college name ? -> ")
Branch = input("Please tell me your branch : ")
Fav_lang = input("Which language is your favourite ? ->")
Year = int(input("What is your current Year ? -> "))
Birth = 2026 - Age
print("--------Student Profile--------")
print("Name: ", Name)
print("Age: ", Age)
print("College: ", College)
print("Branch: ", Branch)
print("Favourite language: ", Fav_lang)
print("Current year: ", Year)
print("Year of birth: ", Birth)
print("Years until graduation: ", 4 - Year)